# -*- coding: utf-8 -*-
"""
Created on 2023-08-18 11:04:26
---------
@summary:
---------
@author: QiuQiuRen
"""

from feapder import UpdateItem


# class YoutubeArtistChannelIdBatchTaskItem(UpdateItem):
#     """
#     This class was generated by feapder
#     command: feapder create -i youtube_artist_channel_id_batch_task 1
#     """

#     __table_name__ = "youtube_artist_channel_id_batch_task"
#     __unique_key__ = ['crawl_condition_youtube_artist_channel_id']
#     __update_key__ = ['crawl_condition_youtube_artist_channel_id','youtube_artist_name']

#     def __init__(self, *args, **kwargs):
#         # self.id = kwargs.get('id')
#         self.youtube_artist_name = None  # youtube艺人名
#         self.youtube_artist_channel_id = None  # youtube艺人频道id
#         # self.parser_name = kwargs.get('parser_name')
#         # self.gtime = kwargs.get('gtime')  # 插入时间

class YoutubeArtistChannelIdBatchDataItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i youtube_artist_channel_id_batch_data 1
    """

    __table_name__ = "youtube_artist_channel_id_batch_data"
    __unique_key__ = ['crawl_condition_youtube_artist_channel_id','youtube_playlist_id']
    __update_key__ = ['crawl_condition_youtube_artist_channel_id','youtube_playlist_id','crawl_result_youtube_artist_channel_id','title','publish_date','batch']

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.crawl_condition_youtube_artist_channel_id = None  # 抓取条件的Youtube艺人频道id
        self.crawl_result_youtube_artist_channel_id = None  # 实际结果的Youtube艺人频道id
        self.youtube_playlist_id = None  # Youtube艺人播放列表
        self.title = None # Youtube播放列表名称
        self.publish_date = None  # Youtube播放列表创建时间
        # self.gtime = kwargs.get('gtime')
        self.batch = None


class YoutubeArtistPlaylistBatchTaskItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i youtube_artist_playlist_batch_task 1
    """

    __table_name__ = "youtube_artist_playlist_batch_task"
    __unique_key__ = ['crawl_condition_youtube_artist_channel_id','youtube_playlist_id']
    __update_key__ = ['crawl_condition_youtube_artist_channel_id','youtube_playlist_id']

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.crawl_condition_youtube_artist_channel_id = None  # 抓取条件的Youtube艺人频道id
        self.youtube_playlist_id = None  # Youtube艺人播放列表
        # self.gtime = kwargs.get('gtime')

class YoutubeArtistPlaylistBatchDataItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i youtube_artist_playlist_batch_data 1
    """

    __table_name__ = "youtube_artist_playlist_batch_data"
    __unique_key__ = ['youtube_playlist_id','youtube_video_id']
    __update_key__ = ['youtube_playlist_id','youtube_video_id','batch']

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.youtube_playlist_id = None  # YouTube播放列表id
        self.youtube_video_id = None  # YouTube视频id
        # self.gtime = kwargs.get('gtime')
        self.batch = None


class YoutubeVideoBatchTaskItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i youtube_video_batch_task 1
    """

    __table_name__ = "youtube_video_batch_task"
    __unique_key__ = ['youtube_video_id']
    __update_key__ = ['youtube_video_id']

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.youtube_video_id = None
        # self.parser_name = kwargs.get('parser_name')
        # self.gtime = kwargs.get('gtime')


class YoutubeVideoBatchDataItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i youtube_video_batch_data 1
    """

    __table_name__ = "youtube_video_batch_data"
    __unique_key__ = ['youtube_video_id','views','like_count','batch']
    __update_key__ = ['youtube_video_id','views','like_count','batch']

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.youtube_video_id = None  # Youtube视频id
        self.views = None  # 视频播放列
        self.like_count = None  # 视频点赞数
        self.batch = None
        # self.gtime = kwargs.get('gtime')

class YoutubeShortsVideoViewsBatchDataItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i youtube_shorts_video_views_batch_data 1
    """

    __table_name__ = "youtube_shorts_video_views_batch_data"
    __unique_key__ = ['youtube_artist_channel_id','youtube_shorts_video_id','youtube_shorts_video_views','batch']
    __update_key__ = ['youtube_artist_channel_id','youtube_artist_name','youtube_shorts_video_id','youtube_shorts_video_views','batch']

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.youtube_artist_channel_id = None
        self.youtube_artist_name = None
        self.youtube_shorts_video_id = None
        self.youtube_shorts_video_views = None
        # self.gtime = kwargs.get('gtime')
        self.batch = None

class YoutubeShortsVideoLikesBatchDataItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i youtube_shorts_video_likes_batch_data 1
    """

    __table_name__ = "youtube_shorts_video_likes_batch_data"
    __unique_key__ = ['youtube_artist_channel_id','youtube_shorts_id','youtube_shorts_video_likes','batch']
    __update_key__ = ['youtube_artist_channel_id','youtube_artist_name','youtube_shorts_id','youtube_shorts_video_likes','batch']


    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.youtube_artist_channel_id = None
        self.youtube_artist_name = None
        self.youtube_shorts_id = None
        self.youtube_shorts_video_likes = None
        # self.youtube_shorts_id=None
        # self.gtime = kwargs.get('gtime')
        self.batch = None

class YoutubeShortsVideoLikesBatchTaskItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i youtube_shorts_video_likes_batch_task 1
    """

    __table_name__ = "youtube_shorts_video_likes_batch_task"
    __unique_key__ = ['youtube_artist_channel_id','youtube_shorts_id']
    __update_key__ = ['youtube_artist_channel_id','youtube_artist_name','youtube_shorts_id']

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.youtube_artist_channel_id = None
        self.youtube_artist_name = None
        self.youtube_shorts_id = None
        # self.state = kwargs.get('state')
        # self.parser_name = kwargs.get('parser_name')


class YoutubeMusicChannelIdBatchDataItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i youtube_music_channel_id_batch_data 1
    """

    __table_name__ = "youtube_music_channel_id_batch_data"
    __unique_key__ = ['youtube_music_channel_id']
    __update_key__ = ['youtube_music_artist_name','youtube_music_channel_name','youtube_music_track_playlist_url','youtube_music_album_single_playlist_url','youtube_music_video_playlist_url','batch']

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.youtube_music_channel_id = None
        self.youtube_music_artist_name = None
        self.youtube_music_channel_name = None
        self.youtube_music_track_playlist_url = None  # YouTube Music歌曲列表链接
        self.youtube_music_album_single_playlist_url = None  # YouTube Music专辑及单曲列表链接
        self.youtube_music_video_playlist_url = None
        self.batch = None
        # self.gtime = kwargs.get('gtime')

class YoutubeMusicChannelIdPlaylistBatchTaskItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i youtube_music_channel_id_playlist_batch_task 1
    """

    __table_name__ = "youtube_music_channel_id_playlist_batch_task"
    __unique_key__ = ['youtube_music_channel_id']
    __update_key__ = ['youtube_music_track_playlist_url','youtube_music_album_single_playlist_url','youtube_music_video_playlist_url']

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.youtube_music_channel_id = None
        self.youtube_music_track_playlist_url = None  # YouTube Music歌曲列表链接
        self.youtube_music_album_single_playlist_url = None  # YouTube Music专辑及单曲列表链接
        self.youtube_music_video_playlist_url = None
        # self.track_playlist_state = kwargs.get('track_playlist_state')
        # self.album_playlist_state = kwargs.get('album_playlist_state')
        # self.single_playlist_state = kwargs.get('single_playlist_state')
        # self.parser_name = kwargs.get('parser_name')
        # self.gtime = kwargs.get('gtime')

class YoutubeMusicChannelIdPlaylistBatchDataItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i youtube_music_channel_id_playlist_batch_data 1
    """

    __table_name__ = "youtube_music_channel_id_playlist_batch_data"
    __unique_key__ = ['youtube_music_channel_id','youtube_music_album_single_playlist_url','youtube_music_album_single_url_pre_redirect','youtube_music_album_single_url']
    __update_key__ = ['youtube_music_channel_id','youtube_music_album_single_playlist_url','youtube_music_album_single_url_pre_redirect','youtube_music_album_single_url','batch']

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.youtube_music_channel_id = kwargs.get('youtube_music_channel_id')
        self.youtube_music_album_single_playlist_url = kwargs.get('youtube_music_album_single_playlist_url')  # Youtube Music 专辑及单曲的综合播放列表链接
        self.youtube_music_album_single_url_pre_redirect = kwargs.get('youtube_music_album_single_url_pre_redirect')  # Youtube Music专辑及单曲的单个链接（重定向前）
        self.youtube_music_album_single_url = kwargs.get('youtube_music_album_single_url')  # Youtube Music专辑及单曲的单个链接（重定向后）
        self.batch = kwargs.get('batch')
        # self.gtime = kwargs.get('gtime')