# -*- coding: utf-8 -*-
"""
Created on 2023-10-09 18:22:36
---------
@summary:
---------
@author: QiuQiuRen
"""

from feapder import UpdateItem


class TempBajaoArtistData001Item(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i temp_bajao_artist_data_001 1
    """

    __table_name__ = "temp_bajao_artist_data_001"
    __update_key__ = ['bajao_artist_id','bajao_artist_name']
    __unique_key__ = ['bajao_artist_id']

    def __init__(self, *args, **kwargs):
        self.bajao_artist_id = None
        self.bajao_artist_name = None
        # self.id = kwargs.get('id')
