# -*- coding: utf-8 -*-
"""
Created on 2023-05-22 16:56:29
---------
@summary:
---------
@author: QiuQiuRen
"""

from feapder import Item


class SearchYoutubeInfoDataItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i search_youtube_info_data 1
    """

    __table_name__ = "search_youtube_info_data"

    def __init__(self, *args, **kwargs):
        self.artist_id = kwargs.get('artist_id')
        self.artist_name = kwargs.get('artist_name')
        self.batch = kwargs.get('batch')
        # self.id = kwargs.get('id')
        self.track_id = kwargs.get('track_id')
        self.track_name = kwargs.get('track_name')
        self.views = kwargs.get('views')
        self.youtube_channel = kwargs.get('youtube_channel')
        self.youtube_link = kwargs.get('youtube_link')
        self.youtube_title = kwargs.get('youtube_title')
        self.youtube_video_id = kwargs.get('youtube_video_id')
