# -*- coding: utf-8 -*-
"""
Created on 2023-10-07 11:31:51
---------
@summary:
---------
@author: QiuQiuRen
"""

from feapder import UpdateItem


class InstagramArtistInfoBatchDataItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i instagram_artist_info_batch_data 1
    """

    __table_name__ = "instagram_artist_info_batch_data"
    __unique_key__ = ['crawl_condition_instagram_artist_url','batch']
    __update_key__ = ['crawl_condition_instagram_artist_name','crawl_condition_instagram_artist_url','crawl_result_instagram_artist_full_name','crawl_result_instagram_artist_name','batch','instagram_artist_followers_count','instagram_artist_image']

    def __init__(self, *args, **kwargs):
        self.batch = None  # 抓取批次日期
        self.crawl_condition_instagram_artist_name = None  # 抓取条件中的歌手名
        self.crawl_condition_instagram_artist_url = None  # 抓取条件的歌手url
        self.crawl_result_instagram_artist_full_name = None  # 歌手全名
        self.crawl_result_instagram_artist_name = None  # 实际抓取结果中的歌手名
        # self.gtime = kwargs.get('gtime')  # 抓取时间
        # self.id = kwargs.get('id')  # id 自动递增
        self.instagram_artist_followers_count = None  # 歌手的粉丝数
        self.instagram_artist_image = None  # 歌手头像
