# -*- coding: utf-8 -*-
"""
Created on 2023-06-28 16:29:14
---------
@summary:
---------
@author: QiuQiuRen
"""

from feapder import Item


class TiktokUserNameBatchDataItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i tiktok_user_name_batch_data 1
    """

    __table_name__ = "tiktok_user_name_batch_data"

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.gmg_artist_id = kwargs.get('gmg_artist_id')  # gmg歌手id
        self.gmg_artist_name = kwargs.get('gmg_artist_name')  # gmg歌手名
        self.user_id = kwargs.get('user_id')  # tiktok用户id(纯数字)
        # self.sec_uid = kwargs.get('sec_uid')  # tiktok用户的sec id(字母数字)
        self.user_name = kwargs.get('user_name')  # tiktok用户链接中的唯一索引
        # self.insert_date = kwargs.get('insert_date')  # 歌手id增量录入时间
        self.tiktok_url = kwargs.get('tiktok_url')
