"""
INSERT INTO chart_data_daily_monitor_record(chart_region,
crawl_chart_country,
batch,
chart_site,
chart_remarks,
chart_segment,
capture_amount,
verified_amount,
checked,
chart_type,
update_frequency,
chart_language,
front_end_web,
api,
web_note,
update_time,
chart_release_date,
error_log)
SELECT chart_region,
crawl_chart_country,
batch,
chart_site,
chart_remarks,
chart_segment,
capture_amount,
verified_amount,
checked,
chart_type,
update_frequency,
chart_language,
front_end_web,
IF(api IS NULL,'-',api) AS 'api',
IF(web_note IS NULL,'-',web_note) AS web_note,
update_time,
chart_release_date,
error_log
FROM Sheet1;
"""