__all__ = [
    "crawl_youtube_api_playlist_info_spider",
    # "crawl_youtube_api_splice_video_task_spider",
    "crawl_youtube_api_video_info_spider",
    "crawl_youtube_artist_channel_page_info_new_spider",
    "crawl_youtube_artist_channel_page_info_spider",
    "crawl_youtube_page_albums_singles_info_new_spider",
    "crawl_youtube_page_albums_singles_info_spider",
    "crawl_youtube_page_featured_on_info_spider",
    "crawl_youtube_page_playlist_info_new_spider",
    "crawl_youtube_page_playlist_info_spider",
    "crawl_youtube_page_songs_info_new_spider",
    "crawl_youtube_page_songs_info_spider",
    "crawl_youtube_page_videos_info_new_spider",
    "crawl_youtube_page_videos_spider",
    "crawl_youtube_playlist_url_redirect_spider",
    "crawl_youtube_video_artist_info_spider",
    "crawl_youtube_video_views_info_spider",
    # "reset_redis_youtube_key"
]