# -*- coding: utf-8 -*-
"""
Created on 2023-09-20 22:37:52
---------
@summary:
---------
@author: AirWolf
"""

from feapder import UpdateItem


class TemporarySearchYoutubeInfoBatchDataItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i temporary_search_youtube_info_batch_data 1
    """

    __table_name__ = "temporary_search_youtube_info_batch_data"
    __unique_key__ = ['artist_id','track_id']
    __update_key__ = ['artist_id','track_id','artist_name','batch','track_name','views','youtube_channel','youtube_link','youtube_title','youtube_video_id']

    def __init__(self, *args, **kwargs):
        self.artist_id = None
        self.artist_name = None
        self.batch = None
        # self.gtime = kwargs.get('gtime')
        # self.id = kwargs.get('id')
        self.track_id = None
        self.track_name = None
        self.views = None
        self.youtube_channel = None
        self.youtube_link = None
        self.youtube_title = None
        self.youtube_video_id = None
