# -*- coding: utf-8 -*-
"""
Created on 2023-09-04 18:44:37
---------
@summary:
---------
@author: QiuQiuRen
"""

from feapder import UpdateItem


class ChartDataDailyBoomplayAfItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i chart_data_daily_boomplay_af 1
    """

    __table_name__ = "chart_data_daily_boomplay_af"

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.rank = kwargs.get('rank')  # 榜单歌曲排名
        self.song_id = kwargs.get('song_id')  # 榜单歌曲id
        self.song_name = kwargs.get('song_name')  # 榜单歌曲名
        self.chart_artist_id = kwargs.get('chart_artist_id')  # 榜单歌手id
        self.chart_artist_name = kwargs.get('chart_artist_name')  # 榜单歌手名
        self.album_id = kwargs.get('album_id')  # 榜单专辑id
        self.album_name = kwargs.get('album_name')  # 榜单专辑名
        self.duration = kwargs.get('duration')  # 歌曲时长
        self.chart_region = kwargs.get('chart_region')  # 抓取国家地区
        self.crawl_chart_country = kwargs.get('crawl_chart_country')  # 抓取国家
        self.batch = kwargs.get('batch')  # 抓取批次
        self.chart_site = kwargs.get('chart_site')  # 抓取网站
        self.chart_type = kwargs.get('chart_type')  # 榜单类型（歌手榜/歌曲榜）
        self.update_frequency = kwargs.get('update_frequency')  # 榜单更新频率
        self.chart_language = kwargs.get('chart_language')  # 榜单语种
        self.chart_segment = kwargs.get('chart_segment')  # 榜单内容数量
        self.chart_release_date = kwargs.get('chart_release_date')  # 榜单本身的更新日期
        self.ranking_state_change = kwargs.get('ranking_state_change')  # 榜单歌曲排名变化
        self.chart_name = kwargs.get('chart_name')  # 榜单名
        self.note = kwargs.get('note')  # 标明数据是北京/非洲
