# -*- coding: utf-8 -*-
"""
Created on 2023-12-13 14:25:04
---------
@summary:
---------
@author: QiuQiuRen
"""

from feapder import UpdateItem


class WikipediaArtistBatchDataItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i wikipedia_artist_batch_data 1
    """

    __table_name__ = "wikipedia_artist_batch_data"
    __update_key__ = ["gmg_artist_name","crawl_condition_artist_name","crawl_box_header_artist_name","gmg_artist_id","sub_artist_name","artist_image","artist_image_description","batch","artist_id","artist_name",
    "artist_info","born","genres","labels","wikipedia_url","years_active","website","occupations","birth_name","origin"]
    __unique_key__ = ["artist_name","batch"]

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.gmg_artist_id = None
        self.gmg_artist_name = None
        self.artist_id = None
        self.artist_name = None
        self.artist_info = None
        self.batch = None
        self.sub_artist_name = None
        self.artist_image = None
        self.artist_image_description = None
        self.crawl_condition_artist_name = None
        self.crawl_box_header_artist_name = None
        self.born = None
        self.genres = None
        self.labels = None
        self.years_active = None
        self.website = None
        self.occupations = None
        self.birth_name = None 
        self.origin = None
        self.wikipedia_url=None
        # self.gtime = kwargs.get('gtime')


class WikipediaArtistCrawlSituationRecordBatchDataItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i wikipedia_artist_crawl_situation_record_batch_data 1
    """

    __table_name__ = "wikipedia_artist_crawl_situation_record_batch_data"
    __update_key__ = ["gmg_artist_name","gmg_artist_id","batch","artist_id","artist_name","artist_infomation_remarks"]
    __unique_key__ = ["artist_name","batch"]

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.gmg_artist_id = None
        self.gmg_artist_name = None
        self.artist_id = None
        self.artist_name = None
        # self.artist_infomation_rules = kwargs.get('artist_infomation_rules')
        self.artist_infomation_remarks = None
        self.batch = None
        # self.gtime = kwargs.get('gtime')


class WikipediaSpotifyArtistBatchDataItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i wikipedia_artist_batch_data 1
    """

    __table_name__ = "wikipedia_spotify_artist_batch_data"
    __update_key__ = ["gmg_artist_name","crawl_condition_artist_name","crawl_box_header_artist_name","gmg_artist_id","sub_artist_name","artist_image","artist_image_description","batch","artist_id","artist_name",
    "artist_info","born","genres","labels","wikipedia_url","years_active","website","occupations","birth_name","origin"]
    __unique_key__ = ["artist_name","batch"]

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.gmg_artist_id = None
        self.gmg_artist_name = None
        self.artist_id = None
        self.artist_name = None
        self.artist_info = None
        self.batch = None
        self.sub_artist_name = None
        self.artist_image = None
        self.artist_image_description = None
        self.crawl_condition_artist_name = None
        self.crawl_box_header_artist_name = None
        self.born = None
        self.wikipedia_url=None
        self.genres = None
        self.labels = None
        self.years_active = None
        self.website = None
        self.occupations = None
        self.birth_name = None 
        self.origin = None
        # self.gtime = kwargs.get('gtime')


class WikipediaSpotifyArtistCrawlSituationRecordBatchDataItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i wikipedia_artist_crawl_situation_record_batch_data 1
    """

    __table_name__ = "wikipedia_spotify_artist_crawl_situation_record_batch_data"
    __update_key__ = ["gmg_artist_name","gmg_artist_id","batch","artist_id","artist_name","artist_infomation_remarks"]
    __unique_key__ = ["artist_name","batch"]

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.gmg_artist_id = None
        self.gmg_artist_name = None
        self.artist_id = None
        self.artist_name = None
        # self.artist_infomation_rules = kwargs.get('artist_infomation_rules')
        self.artist_infomation_remarks = None
        self.batch = None
        # self.gtime = kwargs.get('gtime')