export default {
  language: {
    languageLabel: 'English(United States)'
  },
  baseInfo: {
    orgTypeName255: 'Platform',
    orgTypeName1: 'Clinic',
    orgTypeName2: 'Lab',
    orgTypeName3: 'Individual',
    all: 'All',
    scaned: 'Scaned',
    uploaded: 'Uploaded',
    pending: 'Pending',
    accepted: 'Accepted',
    shipped: 'Shipped',
    completed: 'Completed',
    orderTypeName0: 'Restoration',
    orderTypeName1: 'Orthodontics',
    orderTypeName2: 'Implant'
  },
  login: {
    title: 'Log in',
    logIn: 'Log in',
    userName: 'Email',
    password: 'Password',
    rememberMe: 'Remember Me',
    forgetMe: 'Forget Password',
    signUpTips: 'Sign Up',
    showEmailDialogTitel: 'Password Reset',
    showEmailDialogTips: 'Enter the email address you signed up with and click the "Send Email" button. You will receive an email to reset your password.',
    showEmailDialogPh: 'Enter your email address',
    showEmailDialogCloseBtn: 'Cancel',
    showEmailDialogConfirmBtn: 'Send Email',
    showEmailDialogAlertMsg1: 'The email has been sent to ',
    showEmailDialogAlertMsg2: '. If there is an account associated with the email address you entered, the link for resetting the password might have been sent by email. This link is valid for 24 hours.'
  },
  register: {
    title: 'Create Your Account',
    clinicTitle: 'Clinic',
    clinicLabelTips: 'Administrator',
    clinicAccountTitle: 'Dentist (Manager)',
    clinicAccountDesc: 'All software functions are avai.',
    clinicMemberLabelTips: 'Member',
    clinicMemberAccountTitle: 'Dental Hygienist and Dental Staff',
    clinicMemberAccountDesc: 'In order to use software, join your group as a member. Case management and basic functions will be available after you join the group.',
    labTitle: 'Lab',
    labLabelTips: 'Administrator',
    labAccountTitle: 'Representative/Leader (Manager)',
    labAccountDesc: 'All software functions are available.',
    labMemberLabelTips: 'Member',
    labMemberAccountTitle: 'Laboratory Employees',
    labMemberAccountDesc: 'In order to use software, join your group as a member. Case management and basic functions will be available after you join the group.',
    functionsLabel1: 'Order',
    functionsLabel2: 'Member Management',
    functionsLabel3: 'Order',
    functionsLabel4: 'Oral Scanning',
    functionsLabel5: 'Member Management',
    functionsLabel6: 'Order Management',
    functionsLabel7: 'Sharing work files and production processes.',
    functionsLabel8: 'Order Management',
    signUpButtons: 'Register',
    toLoginLabel: 'Already have an account?',
    toLoginButton: 'Log In'
  },
  registerInfo: {
    orgName: 'Organization Name',
    orgAddress: 'Organization Address',
    clinicName: 'Clinic Name',
    clinicAddress: 'Clinic Address',
    labName: 'Lab Name',
    labAddress: 'Lab Address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    name: 'Name',
    email: 'Email',
    checkBtnText1: 'Check Availability',
    checkBtnText2: 'Seach',
    checkEmailBtnText: 'Check',
    searchBtnText1: 'Check',
    searchBtnText2: 'Seach',
    returnBtnText: 'Back',
    registerBtnText: 'Register',
    typeText: 'Type',
    closeBtnText: 'Close',
    chooseBtnText: 'Use',
    msg1: 'Organization is unavailable',
    msg2: 'Please choose organization',
    msg3: 'Organization is available',
    msg4: 'Please choose clinic',
    msg5: 'Please choose lab',
    msg6: 'This email address is not available.',
    msg7: 'Email address is available',
    msg8: 'Registration successful. The platform will send you a verification email. After verification, you can log in to the platform.',
    msg9: 'Please ensure your email address is valid. The platform will send a verification email.'
  },
  message: {
    messageLevelInfo: 'Info',
    messageLevelWarn: 'Warning',
    messageLevelError: 'Error',
    operationSuccess: 'Success',
    operationFailed: 'Failed',
    requiredValid: 'Required.',
    setLanguageSuccess: 'Set language success.',
    emailValid: 'Email is incorrect.',
    patternValid: 'Input is incorrect.',
    confirmPasswordIsNullValid: 'Please type in the same password as above.',
    confirmPasswordIsMatchValid: '"Password" and "Confirm Password" do not match.',
    loading: 'Loading...'
  },
  menus: {
    dashboard: 'Dashboard',
    myAccount: 'My Info',
    myOrganization: 'My Organization',
    order: 'Case List',
    followcard: 'Partners',
    work: 'Support Request',
    WorkDetail: 'Work Order Details',
    homePage: 'Home Page'
  },
  dashboard: {
    cloudStorageTitle: 'Cloud Storage',
    available: 'Available',
    used: 'Used',
    orderTypeDistributionTitle: 'Order Type Distribution',
    typeName0: 'Orthodontics',
    typeName1: 'Implant',
    typeName2: 'Restoration',
    orderStatusTitle: 'Order Status',
    uploaded: 'Uploaded',
    pending: 'Pending',
    accepted: 'Accepted',
    shipped: 'Shipped',
    completed: 'Completed',
    orderGraphTitle: 'Order Graph',
    options1: 'Last 7 Days',
    options2: 'Last 1 Month',
    options3: 'Last 3 Months',
    graphName: 'Cases'
  },
  myAccount: {
    title: 'My Info',
    title2: 'My Organization',
    labelTitle: 'Account Information',
    emailAddress: 'Email Address',
    passwordLabel: 'Password',
    passwordBtn: 'Change Password',
    name: 'Name',
    saveBtn: 'Save',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    closeBtn: 'Close',
    passwordMsg1: 'The old and new passwords are the same.',
    passwordMsg2: 'The new password and the confirmed password are inconsistent.',
    passwordMsg3: 'Modification successful, please log in again.',
    modifyEmailAddressbtn: 'Modify Email Address',
    modifyEmailAddressTitle: 'Modify Email Address',
    modifyEmailPh: 'New Eamil Address',
    sendEmailBtn: 'Send Email',
    sendEmailMsg1: 'The new email address is the same as the old email address.',
    sendEmailMsg2: 'A confirmation email has been sent to your new inbox. Please check your email.',
    sendEmailMsg3: 'The email is empty or in an incorrect format.',
    acceptSmsNotifsLabel: 'Receive SMS notifications for orders',
    acceptEmailNotifsLabel: 'Receive email notifications for orders'
  },
  myOrganization: {
    title: 'My Info',
    title2: 'My Organization',
    labelTitle1: 'Organization Information',
    labelT1Info1: 'Organization Name',
    labelT1Info2: 'Business Type',
    labelT1Info3: 'Registration',
    autoAcceptApplyBtn: 'Automatically pass the "Partnership Application"',
    labelTitle2: 'Address Information',
    labelT2Info1: 'Address',
    labelT2Info2: 'Contacts',
    labelT2Info3: 'Zip/Postal Code',
    labelT2Info4: 'Office Phone',
    labelT2Info5: 'Mobile Phone',
    labelT2Info6: 'Email',
    labelTitle3: 'About Us',
    labelT3Tip1: 'Select an image to introduce your organization to partners.',
    labelT3Tip2: 'JPG or PNG only. Max size of 4 MB.',
    labelT3Tip3: 'The recommended wide size for a cover image is at leaset 900 px.',
    labelT3Info1: 'Cover Images',
    labelT3Info2: 'Logo',
    labelT3Info3: 'About Us',
    labelT3Info3Placeholder1: 'e.g., Welcome to OOO Dental Clinic.    We are a licensed dental clinic situated in Shanghai specializing mainly in aesthetic restorations and implantology.',
    labelT3Info4: 'Website URL',
    labelT3Info5: 'Terms & Conditions',
    labelT3Info5Placeholder1: 'Please ensure timely delivery of the ordered restorations. For simple cases such as single crowns and inlays, the estimated delivery time should be within 5 working days from the order date; for other complex cases, it should be a maximum of 7 working days. We have high standards for the quality of our restorations. Therefore, if the quality does not meet our standards, there may be multiple requests for remakes.',
    labelT3Info5Tip1: 'You can enter the \'Terms and Conditions\' that your future partners should be aware of here. Please note that this information will be displayed to existing and potential partners in 3ds.',
    labelT3Info6: 'Remark',
    msg1: 'The uploaded image size cannot exceed 4MB!',
    msg2: 'Failed to upload the picture. Please try again later.',
    saveBtn: 'Save'
  },
  order: {
    listQueryPatientPh: 'Patient Name',
    listQueryTypePh: 'Case Type',
    listQueryStartTimePh: 'Scanning Date',
    listQueryEndTimePh: 'Scanning Date',
    searchDataBtn: 'Search',
    clearDataBtn: 'Clear',
    listCreateTime: 'Create Time',
    listScanTime: 'Scanning Date',
    listPatient: 'Patient Name',
    listClinic: 'Clinic',
    listLab: 'Lab',
    listType: 'Type',
    listStatus: 'Status',
    listExpressInfo: 'Shipment',
    listExpressNo: 'Express No',
    listDeliveryTime: 'Delivery Time',
    listBtnLabel: 'Operation',
    listBtnDownload: 'Download',
    listBtnDetail: 'Detail',
    listBtnRemark: 'Remark',
    listBtnCase: 'Send',
    listBtnMade: 'Accept',
    listBtnShip: 'Delivery',
    listBtnCompleted: 'Complete',
    detailDialogLabel: 'Detail',
    detailDialogItem1: 'Order No: ',
    detailDialogItem2: 'Create Time: ',
    detailDialogItem3: 'Scanning Date: ',
    detailDialogItem4: 'Send Operator: ',
    detailDialogItem5: 'Update Time: ',
    detailDialogItem6: 'Updater: ',
    detailDialogItem7: 'Lab Name: ',
    detailDialogItem8: 'Equipment No: ',
    detailDialogItem9: 'Software Version: ',
    detailDialogItem10: 'Status: ',
    detailDialogItem11: 'Patient Name: ',
    detailDialogItem12: 'Type: ',
    detailDialogItem13: 'Other Requirements: ',
    detailDialogItem14: 'Order Remark: ',
    detailDialogItem15: 'Docter: ',
    detailDialogItem16: 'Operator: ',
    screenshotLabel: 'Screenshot',
    previewLabel: 'Preview',
    sendDialogLabel: 'Send',
    cancelBtn: 'Cancel',
    confirmBtn: 'Confirm',
    shipDialogLabel: 'Ship',
    remarkDialogLabel: 'Order Remark',
    shipRulesExpressNo: 'The length should be between 10 and 20 characters.',
    shipDataExpressNoMessage: 'Ship without entering the Express No?',
    shipDataConfirmButtonText: 'Ship',
    shipDataCancelButtonText: 'Cancel',
    downLoadMsg: 'Download patient info failed: '
  },
  partners: {
    tabTitle0: 'Search for Partners',
    tabTitle1: 'My Partner Application',
    tabTitle2: 'My Partner List',
    listQuerySearchPh: 'Enter the name of the organization or press Enter to search.',
    listQuerySearchBtn: 'Search',
    applyBtn: 'Request Partnership',
    cancelBtn: 'Cancel Request',
    pendingBtn: 'Partnership Pending',
    alreadyBtn: 'Already a partner',
    approveBtn: 'Agree to the request',
    rejectBtn: 'Refuse the request',
    removeBtn: 'Break Partnership',
    searchMsg: 'Please enter at least two characters.',
    noResultsMsg: 'No matching partners found, please search again.',
    noResultsBtn: 'Close'
  },
  workOrders: {
    submitOrder: 'Support Request',
    columnLabel1: 'Serial No.',
    columnLabel2: 'Request No.',
    columnLabel3: 'Type',
    columnLabel4: 'Urgency',
    columnLabel5: 'Title',
    columnLabel6: 'Status',
    columnLabel7: 'Submit By',
    columnLabel8: 'Submit Time',
    columnLabel9: 'Last Modify By',
    columnLabel10: 'Modify Time',
    inputLabel1: 'Type',
    inputLabel2: 'Urgency',
    inputLabel3: 'Title',
    inputLabel4: 'Content',
    inputLabel5: 'Image Attachment',
    cancelBtn: 'Cancel',
    submitBtn: 'Submit',
    statusOptionsValue0: 'Submitted',
    statusOptionsValue1: 'Assigned',
    statusOptionsValue2: 'In progress',
    statusOptionsValue3: 'Closed',
    statusOptionsValue4: 'Processed',
    statusOptionsValue5: 'Resolved',
    statusOptionsValue6: 'Unresolved',
    priorityOptionsValue0: 'Normal',
    priorityOptionsValue1: 'Important',
    priorityOptionsValue2: 'Critical',
    typeValue1: 'System issue',
    typeValue2: 'Test work order type',
    typeValue3: 'Test type',
    typeValue4: 'UI issue',
    ruleAlert1: '2-30 characters',
    ruleAlert2: '4-50 characters'
  },
  workDetail: {
    title: 'Communication Record',
    inputLabel1: 'Feedback',
    inputLabel1Ph: 'Please enter feedback',
    btnText1: 'Upload Image',
    btnText2: 'Submit Feedback',
    uploadTip: 'One image uploaded',
    btnClose: 'Close',
    btnDealWith: 'Processed',
    btnSolved: 'Resolved',
    btnUnsolved: 'Unresolved',
    confirmTitle: 'Confirm Information',
    confirmMsg1: 'Are you sure you want to close this work order?',
    confirmMsg2: 'Please confirm if this work order has been processed.',
    confirmMsg3: 'Please confirm if the issue described in this work order has been resolved.',
    confirmMsg4: 'Please confirm if the issue described in this work order is unresolved. If you still have any requirements, please resubmit the work order after submission.'
  },
  userInfo: {
    settingBtn: 'Account Settings',
    logoutBtn: 'Log Out'
  },
  resetPwd: {
    title: 'Password Reset',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    returnBtn: 'Return To Login',
    ruleAlert1: '3-20 characters',
    passwordMsg2: 'The new password and the confirmed password are inconsistent.'
  },
  verifyEmail: {
    title: 'Email Address Confirm',
    confirmBtn: 'Confirm Email Address',
    returnBtn: 'Return To Login'
  },
  modifyEmail: {
    title: 'Modify Email Address',
    confirmBtn: 'Confirm Modify'
  }
}
